sudo: required
language: php
dist: trusty

php:
  - 7.0
  - 7.1

before_script:
  - cp -r .env.travis .env
  - composer install --no-interaction
  - php artisan key:generate

script:
 - vendor/bin/phpunit

services:
  - sqlite

cache:
  directories:
    - vendor

notifications:
  email:
    on_failure: never